// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskSneakerAdviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskSneakerAdviceRequest) Reset() {
	*x = AskSneakerAdviceRequest{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskSneakerAdviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskSneakerAdviceRequest) ProtoMessage() {}

func (x *AskSneakerAdviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskSneakerAdviceRequest.ProtoReflect.Descriptor instead.
func (*AskSneakerAdviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AskSneakerAdviceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AskSneakerAdviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AskSneakerAdviceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AskSneakerAdviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskSneakerAdviceResponse) Reset() {
	*x = AskSneakerAdviceResponse{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskSneakerAdviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskSneakerAdviceResponse) ProtoMessage() {}

func (x *AskSneakerAdviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskSneakerAdviceResponse.ProtoReflect.Descriptor instead.
func (*AskSneakerAdviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AskSneakerAdviceResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *AskSneakerAdviceResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RecommendSneakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   string                 `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Budget        float64                `protobuf:"fixed64,3,opt,name=budget,proto3" json:"budget,omitempty"`
	Size          string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendSneakersRequest) Reset() {
	*x = RecommendSneakersRequest{}
	mi := &file_proto_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendSneakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendSneakersRequest) ProtoMessage() {}

func (x *RecommendSneakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendSneakersRequest.ProtoReflect.Descriptor instead.
func (*RecommendSneakersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendSneakersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendSneakersRequest) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *RecommendSneakersRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *RecommendSneakersRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

type RecommendSneakersResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Recommendations []*SneakerRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendSneakersResponse) Reset() {
	*x = RecommendSneakersResponse{}
	mi := &file_proto_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendSneakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendSneakersResponse) ProtoMessage() {}

func (x *RecommendSneakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendSneakersResponse.ProtoReflect.Descriptor instead.
func (*RecommendSneakersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendSneakersResponse) GetRecommendations() []*SneakerRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type SneakerRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	MatchScore    float64                `protobuf:"fixed64,7,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SneakerRecommendation) Reset() {
	*x = SneakerRecommendation{}
	mi := &file_proto_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SneakerRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SneakerRecommendation) ProtoMessage() {}

func (x *SneakerRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SneakerRecommendation.ProtoReflect.Descriptor instead.
func (*SneakerRecommendation) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SneakerRecommendation) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SneakerRecommendation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SneakerRecommendation) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *SneakerRecommendation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SneakerRecommendation) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SneakerRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SneakerRecommendation) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

type SearchSneakersByStyleRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StyleDescription string                 `protobuf:"bytes,1,opt,name=style_description,json=styleDescription,proto3" json:"style_description,omitempty"`
	Size             string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	MaxPrice         float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchSneakersByStyleRequest) Reset() {
	*x = SearchSneakersByStyleRequest{}
	mi := &file_proto_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSneakersByStyleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSneakersByStyleRequest) ProtoMessage() {}

func (x *SearchSneakersByStyleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSneakersByStyleRequest.ProtoReflect.Descriptor instead.
func (*SearchSneakersByStyleRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSneakersByStyleRequest) GetStyleDescription() string {
	if x != nil {
		return x.StyleDescription
	}
	return ""
}

func (x *SearchSneakersByStyleRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SearchSneakersByStyleRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type SearchSneakersByStyleResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Results       []*SneakerRecommendation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	AiSummary     string                   `protobuf:"bytes,2,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSneakersByStyleResponse) Reset() {
	*x = SearchSneakersByStyleResponse{}
	mi := &file_proto_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSneakersByStyleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSneakersByStyleResponse) ProtoMessage() {}

func (x *SearchSneakersByStyleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSneakersByStyleResponse.ProtoReflect.Descriptor instead.
func (*SearchSneakersByStyleResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{6}
}

func (x *SearchSneakersByStyleResponse) GetResults() []*SneakerRecommendation {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchSneakersByStyleResponse) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

type GetTrendingSneakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingSneakersRequest) Reset() {
	*x = GetTrendingSneakersRequest{}
	mi := &file_proto_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingSneakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingSneakersRequest) ProtoMessage() {}

func (x *GetTrendingSneakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingSneakersRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingSneakersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrendingSneakersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingSneakersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sneakers      []*TrendingSneaker     `protobuf:"bytes,1,rep,name=sneakers,proto3" json:"sneakers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingSneakersResponse) Reset() {
	*x = GetTrendingSneakersResponse{}
	mi := &file_proto_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingSneakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingSneakersResponse) ProtoMessage() {}

func (x *GetTrendingSneakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingSneakersResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingSneakersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrendingSneakersResponse) GetSneakers() []*TrendingSneaker {
	if x != nil {
		return x.Sneakers
	}
	return nil
}

type TrendingSneaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	TrendReason   string                 `protobuf:"bytes,6,opt,name=trend_reason,json=trendReason,proto3" json:"trend_reason,omitempty"`
	TrendScore    int32                  `protobuf:"varint,7,opt,name=trend_score,json=trendScore,proto3" json:"trend_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingSneaker) Reset() {
	*x = TrendingSneaker{}
	mi := &file_proto_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingSneaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingSneaker) ProtoMessage() {}

func (x *TrendingSneaker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingSneaker.ProtoReflect.Descriptor instead.
func (*TrendingSneaker) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{9}
}

func (x *TrendingSneaker) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TrendingSneaker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrendingSneaker) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *TrendingSneaker) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TrendingSneaker) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TrendingSneaker) GetTrendReason() string {
	if x != nil {
		return x.TrendReason
	}
	return ""
}

func (x *TrendingSneaker) GetTrendScore() int32 {
	if x != nil {
		return x.TrendScore
	}
	return 0
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\x02ai\"k\n" +
	"\x17AskSneakerAdviceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\x18AskSneakerAdviceResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x81\x01\n" +
	"\x18RecommendSneakersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vpreferences\x18\x02 \x01(\tR\vpreferences\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x01R\x06budget\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\"`\n" +
	"\x19RecommendSneakersResponse\x12C\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x19.ai.SneakerRecommendationR\x0frecommendations\"\xcc\x01\n" +
	"\x15SneakerRecommendation\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1f\n" +
	"\vmatch_score\x18\a \x01(\x01R\n" +
	"matchScore\"|\n" +
	"\x1cSearchSneakersByStyleRequest\x12+\n" +
	"\x11style_description\x18\x01 \x01(\tR\x10styleDescription\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\"s\n" +
	"\x1dSearchSneakersByStyleResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.ai.SneakerRecommendationR\aresults\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\x02 \x01(\tR\taiSummary\"2\n" +
	"\x1aGetTrendingSneakersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"N\n" +
	"\x1bGetTrendingSneakersResponse\x12/\n" +
	"\bsneakers\x18\x01 \x03(\v2\x13.ai.TrendingSneakerR\bsneakers\"\xd1\x01\n" +
	"\x0fTrendingSneaker\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12!\n" +
	"\ftrend_reason\x18\x06 \x01(\tR\vtrendReason\x12\x1f\n" +
	"\vtrend_score\x18\a \x01(\x05R\n" +
	"trendScore2\xe2\x02\n" +
	"\tAIService\x12M\n" +
	"\x10AskSneakerAdvice\x12\x1b.ai.AskSneakerAdviceRequest\x1a\x1c.ai.AskSneakerAdviceResponse\x12P\n" +
	"\x11RecommendSneakers\x12\x1c.ai.RecommendSneakersRequest\x1a\x1d.ai.RecommendSneakersResponse\x12\\\n" +
	"\x15SearchSneakersByStyle\x12 .ai.SearchSneakersByStyleRequest\x1a!.ai.SearchSneakersByStyleResponse\x12V\n" +
	"\x13GetTrendingSneakers\x12\x1e.ai.GetTrendingSneakersRequest\x1a\x1f.ai.GetTrendingSneakersResponseB%Z#sneaker-store/ai-service/proto;aipbb\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ai_proto_goTypes = []any{
	(*AskSneakerAdviceRequest)(nil),       // 0: ai.AskSneakerAdviceRequest
	(*AskSneakerAdviceResponse)(nil),      // 1: ai.AskSneakerAdviceResponse
	(*RecommendSneakersRequest)(nil),      // 2: ai.RecommendSneakersRequest
	(*RecommendSneakersResponse)(nil),     // 3: ai.RecommendSneakersResponse
	(*SneakerRecommendation)(nil),         // 4: ai.SneakerRecommendation
	(*SearchSneakersByStyleRequest)(nil),  // 5: ai.SearchSneakersByStyleRequest
	(*SearchSneakersByStyleResponse)(nil), // 6: ai.SearchSneakersByStyleResponse
	(*GetTrendingSneakersRequest)(nil),    // 7: ai.GetTrendingSneakersRequest
	(*GetTrendingSneakersResponse)(nil),   // 8: ai.GetTrendingSneakersResponse
	(*TrendingSneaker)(nil),               // 9: ai.TrendingSneaker
}
var file_proto_ai_proto_depIdxs = []int32{
	4, // 0: ai.RecommendSneakersResponse.recommendations:type_name -> ai.SneakerRecommendation
	4, // 1: ai.SearchSneakersByStyleResponse.results:type_name -> ai.SneakerRecommendation
	9, // 2: ai.GetTrendingSneakersResponse.sneakers:type_name -> ai.TrendingSneaker
	0, // 3: ai.AIService.AskSneakerAdvice:input_type -> ai.AskSneakerAdviceRequest
	2, // 4: ai.AIService.RecommendSneakers:input_type -> ai.RecommendSneakersRequest
	5, // 5: ai.AIService.SearchSneakersByStyle:input_type -> ai.SearchSneakersByStyleRequest
	7, // 6: ai.AIService.GetTrendingSneakers:input_type -> ai.GetTrendingSneakersRequest
	1, // 7: ai.AIService.AskSneakerAdvice:output_type -> ai.AskSneakerAdviceResponse
	3, // 8: ai.AIService.RecommendSneakers:output_type -> ai.RecommendSneakersResponse
	6, // 9: ai.AIService.SearchSneakersByStyle:output_type -> ai.SearchSneakersByStyleResponse
	8, // 10: ai.AIService.GetTrendingSneakers:output_type -> ai.GetTrendingSneakersResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
