// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ai.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_AskSneakerAdvice_FullMethodName      = "/ai.AIService/AskSneakerAdvice"
	AIService_RecommendSneakers_FullMethodName     = "/ai.AIService/RecommendSneakers"
	AIService_SearchSneakersByStyle_FullMethodName = "/ai.AIService/SearchSneakersByStyle"
	AIService_GetTrendingSneakers_FullMethodName   = "/ai.AIService/GetTrendingSneakers"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	AskSneakerAdvice(ctx context.Context, in *AskSneakerAdviceRequest, opts ...grpc.CallOption) (*AskSneakerAdviceResponse, error)
	RecommendSneakers(ctx context.Context, in *RecommendSneakersRequest, opts ...grpc.CallOption) (*RecommendSneakersResponse, error)
	SearchSneakersByStyle(ctx context.Context, in *SearchSneakersByStyleRequest, opts ...grpc.CallOption) (*SearchSneakersByStyleResponse, error)
	GetTrendingSneakers(ctx context.Context, in *GetTrendingSneakersRequest, opts ...grpc.CallOption) (*GetTrendingSneakersResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AskSneakerAdvice(ctx context.Context, in *AskSneakerAdviceRequest, opts ...grpc.CallOption) (*AskSneakerAdviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskSneakerAdviceResponse)
	err := c.cc.Invoke(ctx, AIService_AskSneakerAdvice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) RecommendSneakers(ctx context.Context, in *RecommendSneakersRequest, opts ...grpc.CallOption) (*RecommendSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendSneakersResponse)
	err := c.cc.Invoke(ctx, AIService_RecommendSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SearchSneakersByStyle(ctx context.Context, in *SearchSneakersByStyleRequest, opts ...grpc.CallOption) (*SearchSneakersByStyleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSneakersByStyleResponse)
	err := c.cc.Invoke(ctx, AIService_SearchSneakersByStyle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetTrendingSneakers(ctx context.Context, in *GetTrendingSneakersRequest, opts ...grpc.CallOption) (*GetTrendingSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingSneakersResponse)
	err := c.cc.Invoke(ctx, AIService_GetTrendingSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	AskSneakerAdvice(context.Context, *AskSneakerAdviceRequest) (*AskSneakerAdviceResponse, error)
	RecommendSneakers(context.Context, *RecommendSneakersRequest) (*RecommendSneakersResponse, error)
	SearchSneakersByStyle(context.Context, *SearchSneakersByStyleRequest) (*SearchSneakersByStyleResponse, error)
	GetTrendingSneakers(context.Context, *GetTrendingSneakersRequest) (*GetTrendingSneakersResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) AskSneakerAdvice(context.Context, *AskSneakerAdviceRequest) (*AskSneakerAdviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskSneakerAdvice not implemented")
}
func (UnimplementedAIServiceServer) RecommendSneakers(context.Context, *RecommendSneakersRequest) (*RecommendSneakersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendSneakers not implemented")
}
func (UnimplementedAIServiceServer) SearchSneakersByStyle(context.Context, *SearchSneakersByStyleRequest) (*SearchSneakersByStyleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSneakersByStyle not implemented")
}
func (UnimplementedAIServiceServer) GetTrendingSneakers(context.Context, *GetTrendingSneakersRequest) (*GetTrendingSneakersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingSneakers not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_AskSneakerAdvice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskSneakerAdviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AskSneakerAdvice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AskSneakerAdvice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AskSneakerAdvice(ctx, req.(*AskSneakerAdviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_RecommendSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).RecommendSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_RecommendSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).RecommendSneakers(ctx, req.(*RecommendSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SearchSneakersByStyle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSneakersByStyleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SearchSneakersByStyle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SearchSneakersByStyle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SearchSneakersByStyle(ctx, req.(*SearchSneakersByStyleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetTrendingSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetTrendingSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetTrendingSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetTrendingSneakers(ctx, req.(*GetTrendingSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskSneakerAdvice",
			Handler:    _AIService_AskSneakerAdvice_Handler,
		},
		{
			MethodName: "RecommendSneakers",
			Handler:    _AIService_RecommendSneakers_Handler,
		},
		{
			MethodName: "SearchSneakersByStyle",
			Handler:    _AIService_SearchSneakersByStyle_Handler,
		},
		{
			MethodName: "GetTrendingSneakers",
			Handler:    _AIService_GetTrendingSneakers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai.proto",
}
